### ISSUE TITLE
Nextcloudd 20

### ISSUE THREAD

**Issue by f0ma85** [nextcloud/files_fulltextsearch_tesseract#32]
Hello, is there an update planned for nextcloud 20?

**Comment by stoamandl** [comment]
Same question here!
I saw that the last [commit](https://github.com/daita/files_fulltextsearch_tesseract/commit/75844795f07ee5aa55e2958b412bad8265e902f0) made only a change of dependencies to max NC 19.
What about NC 20?
I am not sure if that quick change to version 20 will work.
There are a lot of rebuilds in server back-end logic.

Did anybody tried that?

**Comment by joreiff** [comment]
This app uses multiple features that have been deprecated for Nextcloud 20 (see nextcloud/server#20953). Specifically `$(document).ready(function() {})`, `\OCP\IServerContainer::getEventDispatcher`, `appinfo/app.php` and `OCP\ILogger`. The issue linked above especially advises to replace the jQurey `ready` call (the exact wording is ":warning::boom:", so it is probably important).

**Comment by jacotec** [comment]
The official release of NC 20 is 7 weeks old by now, beta not counted. It's somewhat annoying that I always need to wait for fulltext search for nearly two months after a release :(

Any schedule here?

**Comment by plinss** [comment]
@jacotec Here's something you might benefit from reading: https://journal.neilgaiman.com/2009/05/entitlement-issues.html

To paraphrase Neil Gaiman: @daita is not your bitch.

This is open source software. As far as I know, you have not paid for it, and @daita is not on your payroll, nor are they your property. Therefore, they don't owe you anything. I appreciate that this is inconvenient for you, and understand that you're annoyed. This is blocking me upgrading as well. Taking it out on the author does not help.

You're more than welcome to:
1) voice your support for the update (politely, simply clicking the thumbs-up button above works).
2) offer the author money or other support to help make the update a prioity.
3) do the update yourself and contribute a patch.
4) pay someone else to do the update and contribute a patch.
5) wait patiently.

As an open-source author myself, I can tell you that: pestering, berating, or venting at an author, who donated their time and hard work for nothing in return, tends to get work de-prioritized, or even dropped.

Open-source software thrives when there is a supporting community. Please be part of one.

&lt;/rant>

**Comment by jacotec** [comment]
@plinss I did not offend anyone, and the very last thing I'd do is to offend @daita or any other author/contributor. So why do you offend me by telling me I'd think of daita being "my bitch" or "my property"? I'd recommend to reconsider your wording!

**Comment by plinss** [comment]
@jacotec I accept that you may not have _intended_ offense, but it is the person on the receiving end that determines if they were offended, not the giver of offense. The onus is on you to ensure your words match your intention. I, for one, was offended by your tone to the extent that I felt a response was warranted (I accept that this is a hot-button topic for me, but if you actually read the blog post I linked, you'll understand my choice of words). 

If you did not intend offense, I suggest you reconsider **your** wording. You could have simply asked for an update, no need to state the amount of time that has passed, express your annoyance and displeasure, or put blame on the author for your inability to update.

**Comment by jacotec** [comment]
@plinss I've edited my post, not because of your aggressive comment but to prevent that @daita misunderstands it, which is not my intention.

@plinss If you think that someone's comment could be misunderstood or appears unfriendly to you, a friendly hint is always welcome and has more effect than pulling the Bazooka and shoot right away! I don't think Daita or anyone else wants you to be his personal Rambo.
When you write "be part of one", start sweeping in front of your own door. Netiquette is also a part of it

**Comment by jacotec** [comment]
... just a polite question if this project is still active?

**Comment by daita** [comment]
yes, a release for nc20 should be available

**Comment by epvuc** [comment]
I and a couple of other people have found that on updating a 19.0.6 installation to 20.0.3, indexing new documents fails when fulltextsearch_tesseract is enabled. (see https://github.com/nextcloud/files_fulltextsearch/issues/100)

Apologies if this was already known - i just didn't know it didn't work in nc20 so I was confused when it broke.  Should it maybe be marked as incompatible with nc20 so users can avoid updating if they want?

**Comment by SimJoSt** [comment]
Support for Nextcloud Version 20 was added in the following commit and tag:
- https://github.com/nextcloud/files_fulltextsearch_tesseract/commit/05761b60ad4b7b39eac6f0f46c15e22ea9fe0b68
- https://github.com/nextcloud/files_fulltextsearch_tesseract/releases/tag/v20.0.0

Closing this, the original issue is resolved, reported problems are likely to be superseded and should be in their own issue anyway.
