### ISSUE TITLE
Nextcloud 21 Support

### ISSUE THREAD

**Issue by vapaa** [nextcloud/files_fulltextsearch_tesseract#36]
Please check for Nextcloud 21 Support.

Thanks

**Comment by plinss** [comment]
I see the release for Nexcloud 21 happened two days ago, but it's not showing up in the Nextcloud app store yet...

**Comment by belzebub40k** [comment]
Is there an ETA when the new version will be available on apps.nextcloud.com?

**Comment by jippi** [comment]
Soft bump on this - 21.0.1 are now being pushed to "stable" users :)

**Comment by morbificagent** [comment]
Its the only app because of which i cant upgrade to v21 :-(

**Comment by dolohow** [comment]
I use it with v21 and I think it works fine

**Comment by morbificagent** [comment]
but how can i upgrade to 21 if the updater says "the tresseract-app isnt availible for 21"

I have installed it from the NC Appstore but there isnt a version for  NC 21...

**Comment by belzebub40k** [comment]
The app gets deactivated during the update but you can re-enable after the update.

**Comment by joreiff** [comment]
@daita It seems that support for Nextcloud 21 has been added on March 8. The app, however, has not been released on the Nextcloud App Store. Was this an oversight? Or is there still some work left?

**Comment by SimJoSt** [comment]
Support for Nextcloud Version 21 was added in the following commit and tag:
- https://github.com/nextcloud/files_fulltextsearch_tesseract/commit/def4791c82cfe07f4c8f9ec979afc3d65272070f
- https://github.com/nextcloud/files_fulltextsearch_tesseract/releases/tag/v22.0.0
