### ISSUE TITLE
Support for Nexcloud 25

### ISSUE THREAD

**Issue by jacotec** [nextcloud/files_fulltextsearch_tesseract#52]
Nextcloud 25 is out a while and the fulltextsearch apps are currently blocking my update ...

**Comment by SimJoSt** [comment]
Support for Nextcloud version 25 (alpha) was added in the following commit and tag:
- https://github.com/nextcloud/files_fulltextsearch_tesseract/commit/b732417046477649220986ee4bf06c24f5c8465b
- https://github.com/nextcloud/files_fulltextsearch_tesseract/releases/tag/25.0.0
