### ISSUE TITLE
Compability for NC 26

### ISSUE THREAD

**Issue by RunnerLexico** [nextcloud/files_fulltextsearch_tesseract#53]
Nextcloud 26 is out and the fulltextsearch apps are not compatible yet.

Does it work with Nextcloud 26?

Thanks and regards

**Comment by RealCommerzpunk** [comment]
Hello, i like to know this too, does anyboby have the answer?

**Comment by JVKeller** [comment]
I'm thinking no. I just installed it on 27, and there's nowhere to access it. It shows up as an installed app but that's about it.

**Comment by mf-in-mun** [comment]
Same here!

And first of all: Thanks for the good work.

**Comment by madman2012** [comment]
Same question, is it compatible with NC 26?

**Comment by TedfromZed** [comment]
Hi folks, just did a check and et voilà...

![image](https://github.com/nextcloud/files_fulltextsearch_tesseract/assets/135044779/42351994-7a4e-4b95-bcfb-2003db45d085)

Thank you, you almighty Gods, for taking some of your precious time and gifting us the much needed compatibility. 

Now carry on, my wayward son, update 26 will soon be done!

**Comment by mf-in-mun** [comment]
First of all: Thank's a lot to the maintainer(s) 👍👍👍👍👍👍

I've done the update to NC26 this morning and so far it works.
I will monitor it over the next days.

And as far as I understand it's also compatible with NC27, so next update could be done immediately!

Again Thank's a lot and best regards
